{
    'name': 'Stock Account Module Enchanced',
    'summary': 'Stock Account Module',
    'version': '8.0.0.1.0',
    'author': "Jakc Labs,Odoo Community Association (OCA)",
    'category': 'Customer',
    'license': 'AGPL-3',
    'complexity': 'normal',
    'images': [],
    'website': "http://www.jakc-labs.com",
    'demo': [],    
    'depends': [],
    'application': True,
    'data':[],
    'installable': True,
    'application': True,
}